# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  boot.kernel.sysctl = {
    "vm.nr_hugepages" = 512;
  };

  fileSystems."/" =
    { device = "/dev/mapper/luks-ea12fa30-db47-4271-8897-e80a2bad39c4";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-ea12fa30-db47-4271-8897-e80a2bad39c4".device = "/dev/disk/by-uuid/ea12fa30-db47-4271-8897-e80a2bad39c4";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/B3CC-ADCE";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-b36d9cf3-a23a-47a2-8014-d493a8d6f6d2"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  
  # For offloading, `modesetting` is needed additionally,
  # otherwise the X-server will be running permanently on nvidia,
  # thus keeping the GPU always on (see `nvidia-smi`).
  services.xserver.videoDrivers = [ 
    "modesetting" # for Intel iGPU
    "nvidia" 
  ];

  hardware.graphics = {
    # Enable OpenGL 
    enable = true;

    extraPackages = with pkgs; [
      # Required for modern Intel GPUs (Xe iGPU and ARC)
      intel-media-driver     # VA-API (iHD) userspace
      vpl-gpu-rt             # oneVPL (QSV) runtime

      # Optional (compute / tooling):
      intel-compute-runtime  # OpenCL (NEO) + Level Zero for Arc/Xe
      # NOTE: 'intel-ocl' also exists as a legacy package; not recommended for Arc/Xe.
      # libvdpau-va-gl       # Only if you must run VDPAU-only apps
    ];
  };

  hardware.nvidia = {
    open = true;
    package = config.boot.kernelPackages.nvidiaPackages.stable; # Default
    prime = {
      offload.enable = true;

      intelBusId = "PCI:0@0:2:0";
      nvidiaBusId = "PCI:1@0:0:0";
    };
    modesetting.enable = true;
  };

  environment.sessionVariables = {
    LIBVA_DRIVER_NAME = "iHD";     # Prefer the modern iHD backend
    # VDPAU_DRIVER = "va_gl";      # Only if using libvdpau-va-gl
  };

  # May help services that have trouble accessing /dev/dri (e.g., jellyfin/plex):
  # users.users.<service>.extraGroups = [ "video" "render" ];

  zramSwap = {
    enable = true;
    memoryMax = 8 * 1024 * 1024 * 1024;  # 16 GB ZRAM
  };

  hardware.bluetooth = {
    enable = true;
    powerOnBoot = true;
    settings = {
      General = {
	# Shows battery charge of connected devices on supported
	# Bluetooth adapters. Defaults to 'false'.
	Experimental = true;
	# When enabled other devices can connect faster to us, however
	# the tradeoff is increased power consumption. Defaults to
	# 'false'.
	FastConnectable = true;
      };
      Policy = {
	# Enable all controllers when they are found. This includes
	# adapters present on start as well as adapters that are plugged
	# in later on. Defaults to 'true'.
	AutoEnable = true;
      };
    };
  };
}
