# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-5a092d91-f04f-4e5f-9f00-1eba45232a6b";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-5a092d91-f04f-4e5f-9f00-1eba45232a6b".device = "/dev/disk/by-uuid/5a092d91-f04f-4e5f-9f00-1eba45232a6b";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/3714-E43E";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-3323d187-34de-4c09-a594-f0e52f4bf5a7"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
